export const Wgt_Depotwise_Data = [
    {
      id: 1,
      depot: "Delhi-Naraina",
      territorys: "6", 
      dealers: "116",  
      wt: "10",
      ly: "100",
      target: "126",
      target_percentage: "26",
      achieved: "60",
      achieved_percentage: "12",
    },  
    {
      id: 2,
      depot: "Ambala",
      territorys: "5", 
      dealers: "146", 
      ly: "100", 
      wt: "7",
      target: "126",
      target_percentage: "26",
      achieved: "60",
      achieved_percentage: "12",
    },  

    {
      id: 3,
      depot: "Gurgaon",
      territorys: "5", 
      dealers: "146", 
      ly: "100", 
      wt: "3",
      target: "126",
      target_percentage: "26",
      achieved: "60",
      achieved_percentage: "12",
    },    

    {
      id: 4,
      depot: "Jalandhar",
      territorys: "5", 
      dealers: "146", 
      ly: "100", 
      wt: "6",
      target: "126",
      target_percentage: "26",
      achieved: "60",
      achieved_percentage: "12",
    },  


    {
      id: 5,
      depot: "Jammu",
      territorys: "5", 
      dealers: "146", 
      ly: "100", 
      wt: "4",
      target: "126",
      target_percentage: "26",
      achieved: "60",
      achieved_percentage: "12",
    },  


    {
      id: 6,
      depot: "Ludhiana",
      territorys: "5", 
      dealers: "146", 
      ly: "100", 
      wt: "5",
      target: "126",
      target_percentage: "26",
      achieved: "60",
      achieved_percentage: "12",
    },  


    {
      id: 7,
      depot: "Nebsarai",
      territorys: "5", 
      dealers: "146", 
      ly: "100", 
      wt: "15",
      target: "126",
      target_percentage: "26",
      achieved: "60",
      achieved_percentage: "12",
    },    


    {
      id: 8,
      depot: "Zirakpur [Himachal]",
      territorys: "5", 
      dealers: "146", 
      ly: "100", 
      wt: "11",
      target: "126",
      target_percentage: "26",
      achieved: "60",
      achieved_percentage: "12",
    },    


    {
      id: 9,
      depot: "Zirakpur",
      territorys: "5", 
      dealers: "146", 
      ly: "100", 
      wt: "9",
      target: "126",
      target_percentage: "26",
      achieved: "60",
      achieved_percentage: "12",
    },  
  ];